name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USER: mateouni
      IMAGE_NAME: my-backend-app
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Login with your secret
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKER_HUB_CREDENTIALS_DOMAIN_TO_GIT_HUB_BACKEND }}

      - name: Build image
        run: |
          docker build -t $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push image
        run: |
          docker push $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG
